/** Codes d’exécution de simulation (Lot 2B-3). */

export type CampaignSimulationExecutionCode =
  | "SIMULATION_CONFIGURATION_NOT_VALIDATED"
  | "SIMULATION_CONFIGURATION_STALE"
  | "SIMULATION_INPUTS_CHANGED_AFTER_VALIDATION"
  | "SIMULATION_EXECUTION_FAILED"
  | "SIMULATION_ENGINE_FAILED"
  | "SIMULATION_RESULT_INCOMPLETE"
  | "CAMPAIGN_NOT_FOUND"
  | "CAMPAIGN_ARCHIVED"
  | "SIMULATION_NOT_READY"
  | "SIMULATION_ALREADY_RUNNING";
