/** Codes de sauvegarde / lecture d’historique de simulation (Lot 2B-4A). */

export type SimulationPersistenceCode =
  | "SIMULATION_RESULT_NOT_AVAILABLE"
  | "SIMULATION_RESULT_STALE"
  | "SIMULATION_RESULT_CAMPAIGN_MISMATCH"
  | "SIMULATION_CONFIGURATION_MISMATCH"
  | "SIMULATION_INPUTS_CHANGED_BEFORE_SAVE"
  | "CAMPAIGN_ARCHIVED"
  | "CURRENT_IMPORT_BATCH_CHANGED"
  | "SIMULATION_SAVE_FAILED"
  | "SIMULATION_RUN_NOT_FOUND"
  | "SIMULATION_HISTORY_READ_FAILED";
