/** Codes de configuration UI simulation (Lot 2B-2) — sans dupliquer le moteur 2A. */

export type SimulationConfigurationCode =
  | "MISSING_CAMPAIGN_SELECTION"
  | "MISSING_BUDGET_TARGET_MODE"
  | "MISSING_MANUAL_BUDGET"
  | "INVALID_MANUAL_BUDGET"
  | "MISSING_ELIGIBLE_PAYROLL"
  | "INVALID_ELIGIBLE_PAYROLL"
  | "MISSING_BUDGET_RATE"
  | "INVALID_BUDGET_RATE"
  | "MISSING_ROUNDING_MODE"
  | "MISSING_ROUNDING_STEP"
  | "INVALID_ROUNDING_STEP"
  | "CONFIGURATION_NOT_READY"
  | "CONFIGURATION_CHANGED_AFTER_VALIDATION"
  | "CAMPAIGN_CONFIGURATION_READ_ONLY"
  // Lot 2A-H2A — calendrier d’application
  | "MISSING_CAMPAIGN_YEAR"
  | "INVALID_CAMPAIGN_YEAR"
  | "MISSING_TECHNICAL_APPLICATION_MONTH"
  | "INVALID_TECHNICAL_APPLICATION_MONTH"
  // Lot 2A-H2D-1 — rétroactivité configurable
  | "MISSING_RETROACTIVITY_START_MONTH"
  | "INVALID_RETROACTIVITY_START_MONTH"
  | "RETROACTIVITY_MONTH_AFTER_APPLICATION_MONTH"
  | "SIMULATION_SNAPSHOT_SCHEMA_REQUIRES_CONSOLIDATION"
  // Lot 2A-H2D-2 — minimum garanti
  | "MISSING_MINIMUM_INCREASE_MODE"
  | "UNSUPPORTED_MINIMUM_INCREASE_MODE"
  | "INVALID_MINIMUM_INCREASE_CONFIGURATION"
  | "MISSING_MINIMUM_MONTHLY_AMOUNT"
  | "INVALID_MINIMUM_MONTHLY_AMOUNT"
  | "MISSING_MINIMUM_INCREASE_RATE"
  | "INVALID_MINIMUM_INCREASE_RATE"
  | "MINIMUM_GUARANTEE_EXCEEDS_BUDGET"
  // Lot 2B-RC1-H4 — mois d’effet du minimum garanti
  | "MISSING_MINIMUM_GUARANTEE_EFFECTIVE_MONTH"
  | "INVALID_MINIMUM_GUARANTEE_EFFECTIVE_MONTH";
